// Basic style tokens to align dynamic form with reference screenshot
export const styleTokens = {
  outer: 'mx-auto max-w-5xl bg-white rounded-xl border border-orange-100 shadow-sm overflow-hidden',
  headerTitle: 'text-2xl font-semibold tracking-tight text-gray-800',
  headerDesc: 'text-gray-600',
  sectionWrap: 'px-8 pt-4',
  sectionHeaderRow: 'flex items-center gap-3 mb-2',
  sectionAccent: 'h-5 w-1.5 rounded-sm bg-orange-600',
  sectionTitle: 'text-xl font-semibold text-gray-800',
  sectionDivider: 'h-px bg-orange-100 mb-6',
  grid: 'grid gap-8 md:grid-cols-2',
  fieldBlock: 'space-y-2',
  label: 'text-sm font-medium text-gray-700',
  badgeNumber: 'inline-flex h-5 w-5 items-center justify-center rounded-full bg-orange-600 text-white text-[11px] font-semibold mr-1',
  input: 'h-10 w-full rounded-md border border-gray-300 bg-white px-3 text-sm focus:outline-none focus:ring-2 focus:ring-orange-500/40 focus:border-orange-500 transition',
  textarea: 'w-full rounded-md border border-gray-300 bg-white px-3 py-2 text-sm min-h-[110px] resize-vertical focus:outline-none focus:ring-2 focus:ring-orange-500/40 focus:border-orange-500 transition',
  attachmentsMeta: 'text-[10px] font-mono text-gray-400 break-all',
  attachmentItem: 'rounded-md border border-orange-200 bg-orange-50/40 p-3',
  progressBarWrap: 'mt-1 w-full h-1.5 rounded bg-orange-100 overflow-hidden',
  actionsBar: 'mt-10 border-t border-orange-100 bg-gradient-to-r from-white via-orange-50/50 to-white px-8 py-6 flex flex-col sm:flex-row-reverse gap-4 sm:items-center',
  primaryBtn: 'h-11 w-full sm:w-auto px-10 bg-orange-600 hover:bg-orange-700 text-white font-semibold rounded-md shadow-sm disabled:opacity-60 transition',
  secondaryBtn: 'h-11 w-full sm:w-auto px-6 font-medium border border-gray-300 text-gray-700 rounded-md hover:bg-gray-50 transition',
  tertiaryBtn: 'h-11 w-full sm:w-auto px-6 font-medium border border-orange-200 text-orange-700 rounded-md hover:bg-orange-50 transition',
}
