// Basic style tokens to align dynamic form with reference screenshot
export const styleTokens = {
  // Switched from orange palette to blue palette
  outer: 'mx-auto max-w-5xl bg-white rounded-xl border border-blue-100 shadow-sm overflow-hidden',
  headerTitle: 'text-3xl font-semibold tracking-tight text-gray-800',
  headerDesc: 'text-base text-gray-600',
  sectionWrap: 'px-8 pt-4',
  sectionHeaderRow: 'flex items-center gap-3 mb-2',
  sectionAccent: 'h-5 w-1.5 rounded-sm bg-blue-600',
  sectionTitle: 'text-2xl font-semibold text-gray-800',
  sectionDivider: 'h-px bg-blue-100 mb-6',
  grid: 'grid gap-6 md:grid-cols-2 md:gap-x-8 md:gap-y-6',
  fieldBlock: 'space-y-2 w-full',
  label: 'text-base font-medium text-gray-700',
  badgeNumber: 'inline-flex h-6 w-6 items-center justify-center rounded-full bg-blue-600 text-white text-xs font-semibold mr-1',
  input: 'h-11 w-full rounded-md border border-gray-300 bg-white px-3 text-base focus:outline-none focus:ring-2 focus:ring-blue-500/40 focus:border-blue-500 transition',
  textarea: 'w-full rounded-md border border-gray-300 bg-white px-3 py-3 text-base min-h-[120px] resize-vertical focus:outline-none focus:ring-2 focus:ring-blue-500/40 focus:border-blue-500 transition leading-relaxed',
  attachmentsMeta: 'text-[10px] font-mono text-gray-400 break-all',
  attachmentItem: 'rounded-md border border-blue-200 bg-blue-50/40 p-3',
  progressBarWrap: 'mt-1 w-full h-1.5 rounded bg-blue-100 overflow-hidden',
  actionsBar: 'mt-10 border-t border-blue-100 bg-gradient-to-r from-white via-blue-50/50 to-white px-8 py-6 flex flex-col sm:flex-row-reverse gap-4 sm:items-center',
  primaryBtn: 'h-11 w-full sm:w-auto px-10 bg-blue-600 hover:bg-blue-700 text-white font-semibold rounded-md shadow-sm disabled:opacity-60 transition',
  secondaryBtn: 'h-11 w-full sm:w-auto px-6 font-medium border border-gray-300 text-gray-700 rounded-md hover:bg-gray-50 transition',
  tertiaryBtn: 'h-11 w-full sm:w-auto px-6 font-medium border border-blue-200 text-blue-700 rounded-md hover:bg-blue-50 transition',
}
